-- ============================================================
-- COMSED (КОМСЕД) - Онлайн магазин за детски играчки
-- DDL Script за DB2
-- Схема: FN2MI0700362
-- Автор: Стас Узунов, ф.н. 2MI0700362
-- ============================================================

SET SCHEMA FN2MI0700362;

-- ============================================================
-- 1. CATEGORY
-- ============================================================
CREATE TABLE CATEGORY (
    CATEGORY_ID   INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME          VARCHAR(255)  NOT NULL,
    SLUG          VARCHAR(255)  NOT NULL,
    PARENT_ID     INTEGER,
    DESCRIPTION   VARCHAR(1000),
    IS_ACTIVE     SMALLINT      NOT NULL DEFAULT 1,
    CONSTRAINT PK_CATEGORY       PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UQ_CATEGORY_SLUG  UNIQUE (SLUG),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (CATEGORY_ID) ON DELETE SET NULL,
    CONSTRAINT CK_CATEGORY_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- ============================================================
-- 2. PRODUCT
-- ============================================================
CREATE TABLE PRODUCT (
    PRODUCT_ID    INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME          VARCHAR(500)  NOT NULL,
    SKU           VARCHAR(100)  NOT NULL,
    PRICE         DECIMAL(10,2) NOT NULL,
    PROMO_PRICE   DECIMAL(10,2),
    QTY_IN_STOCK  INTEGER       NOT NULL DEFAULT 0,
    BRAND_ID      VARCHAR(100),
    IS_ACTIVE     SMALLINT      NOT NULL DEFAULT 1,
    CONSTRAINT PK_PRODUCT        PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT UQ_PRODUCT_SKU    UNIQUE (SKU),
    CONSTRAINT CK_PRODUCT_PRICE  CHECK (PRICE > 0),
    CONSTRAINT CK_PRODUCT_PROMO  CHECK (PROMO_PRICE IS NULL OR (PROMO_PRICE > 0 AND PROMO_PRICE < PRICE)),
    CONSTRAINT CK_PRODUCT_QTY    CHECK (QTY_IN_STOCK >= 0),
    CONSTRAINT CK_PRODUCT_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- ============================================================
-- 3. CUSTOMER
-- ============================================================
CREATE TABLE CUSTOMER (
    CUSTOMER_ID   INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FIRST_NAME    VARCHAR(100)  NOT NULL,
    LAST_NAME     VARCHAR(100)  NOT NULL,
    EMAIL         VARCHAR(255)  NOT NULL,
    PHONE         VARCHAR(20),
    CONSTRAINT PK_CUSTOMER        PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMER_EMAIL  UNIQUE (EMAIL)
);

-- ============================================================
-- 4. ORDERS (избягваме запазената дума ORDER)
-- ============================================================
CREATE TABLE ORDERS (
    ORDER_ID        INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    STATUS          VARCHAR(20)   NOT NULL DEFAULT 'pending',
    TOTAL           DECIMAL(10,2) NOT NULL,
    PAYMENT_METHOD  VARCHAR(20)   NOT NULL,
    DELIVERY_METHOD VARCHAR(20)   NOT NULL,
    CREATED_AT      TIMESTAMP     NOT NULL DEFAULT CURRENT TIMESTAMP,
    CUSTOMER_ID     INTEGER       NOT NULL,
    CONSTRAINT PK_ORDERS            PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_CUSTOMER   FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID) ON DELETE RESTRICT,
    CONSTRAINT CK_ORDERS_STATUS     CHECK (STATUS IN ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
    CONSTRAINT CK_ORDERS_TOTAL      CHECK (TOTAL >= 0),
    CONSTRAINT CK_ORDERS_PAYMENT    CHECK (PAYMENT_METHOD IN ('cod', 'card', 'bank_transfer')),
    CONSTRAINT CK_ORDERS_DELIVERY   CHECK (DELIVERY_METHOD IN ('courier', 'store_pickup', 'econt', 'speedy'))
);

-- ============================================================
-- 5. ORDER_ITEM
-- ============================================================
CREATE TABLE ORDER_ITEM (
    ORDER_ITEM_ID INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    QUANTITY      INTEGER       NOT NULL,
    UNIT_PRICE    DECIMAL(10,2) NOT NULL,
    PROMO_PRICE   DECIMAL(10,2),
    ORDER_ID      INTEGER       NOT NULL,
    PRODUCT_ID    INTEGER       NOT NULL,
    CONSTRAINT PK_ORDER_ITEM          PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDER_ITEM_ORDER    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_PRODUCT  FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE RESTRICT,
    CONSTRAINT CK_ORDER_ITEM_QTY      CHECK (QUANTITY >= 1),
    CONSTRAINT CK_ORDER_ITEM_PRICE    CHECK (UNIT_PRICE > 0)
);

-- ============================================================
-- 6. PROMOTION
-- ============================================================
CREATE TABLE PROMOTION (
    PROMOTION_ID  INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    NAME          VARCHAR(255)  NOT NULL,
    DISCOUNT_PCT  DECIMAL(5,2),
    START_DATE    DATE          NOT NULL,
    END_DATE      DATE          NOT NULL,
    IS_ACTIVE     SMALLINT      NOT NULL DEFAULT 1,
    CONSTRAINT PK_PROMOTION           PRIMARY KEY (PROMOTION_ID),
    CONSTRAINT CK_PROMOTION_DISC      CHECK (DISCOUNT_PCT IS NULL OR (DISCOUNT_PCT > 0 AND DISCOUNT_PCT <= 100)),
    CONSTRAINT CK_PROMOTION_DATES     CHECK (END_DATE >= START_DATE),
    CONSTRAINT CK_PROMOTION_ACTIVE    CHECK (IS_ACTIVE IN (0, 1))
);

-- ============================================================
-- 7. PRODUCT_CATEGORY (M:N връзка)
-- ============================================================
CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_ID    INTEGER NOT NULL,
    CATEGORY_ID   INTEGER NOT NULL,
    CONSTRAINT PK_PROD_CAT          PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
    CONSTRAINT FK_PROD_CAT_PROD     FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROD_CAT_CAT      FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID) ON DELETE CASCADE
);

-- ============================================================
-- 8. PRODUCT_PROMOTION (M:N връзка)
-- ============================================================
CREATE TABLE PRODUCT_PROMOTION (
    PRODUCT_ID    INTEGER NOT NULL,
    PROMOTION_ID  INTEGER NOT NULL,
    CONSTRAINT PK_PROD_PROMO          PRIMARY KEY (PRODUCT_ID, PROMOTION_ID),
    CONSTRAINT FK_PROD_PROMO_PROD     FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PROD_PROMO_PROMO    FOREIGN KEY (PROMOTION_ID) REFERENCES PROMOTION (PROMOTION_ID) ON DELETE CASCADE
);
